apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xo-pangolin.fullname" . }}-pangolin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: pangolin
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: pangolin
        app: {{ include "xo-pangolin.fullname" . }}-pangolin
    spec:
      containers:
        - image: "{{ .Values.deployments.pangolin.image.repository }}:{{ .Values.deployments.pangolin.image.tag }}"
          imagePullPolicy: "{{ .Values.deployments.pangolin.image.pullPolicy }}"
          name: pangolin
          readinessProbe:
            failureThreshold: 15
            httpGet:
              path: /api/v1/
              port: 3001
              scheme: HTTP

          {{- $vols := required "values.volumes must be a non-empty list" .Values.volumes }}
          {{- $first := required "values.volumes[0] is missing" (index $vols 0) }}
          {{- $volName := required "values.volumes[0].name is required" $first.name }}
          volumeMounts:
            - mountPath: /var/certificates
              name: {{ $volName }}
              subPath: pangolin-data
            - mountPath: /var/dynamic
              name: {{ $volName }}
              subPath: pangolin-data
            - mountPath: /app/config
              name: {{ $volName }}
              subPath: config
            - mountPath: /app/config/config.yml
              name: config-file
              subPath: config.yml
      volumes:
        {{- toYaml $vols | nindent 8 }}
        - name: config-file
          secret:
            secretName: {{ include "xo-pangolin.fullname" . }}-config
